modLoader = "javafml" #mandatory
# javafml 语言提供者版本（FML Implementation-Version），不是 NeoForge 版本号
loaderVersion = "${javafml_loader_version_range}" #mandatory
license = "${license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "assets/${mod_id}/logo.png"
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory

[modproperties.${mod_id}]
configuredBackground = "minecraft:textures/block/deepslate.png"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

# 1.20.5+：dependency 使用 type=required，禁止 mandatory=
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type = "required"
versionRange = "${neoforge_loader_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
