#!/usr/bin/env python3
"""Expand Manifold #if directives into plain Java for JDT-based tools.

JDT Language Server (ECJ) has no preprocessor concept, so Manifold sources
(#if MC_VER < MC_1_21_5) produce cascading syntax errors. This script evaluates
the directive stack against a target MC version and writes a plain-Java copy of
the source tree that jdtls can consume without false positives.

Constants come from build.properties (generated by the Gradle build), e.g.:
    MC_1_20_1=0  ...  MC_1_21_11=16   MC_VER=<current version index>

Usage:
    python scripts/manifold-expand.py 1.20.4
    python scripts/manifold-expand.py --mc-ver 3 --defs build.properties \
        --out build/jdt-view/1.20.4 common fabric forge neoforge
"""

import argparse
import ast
import operator
import re
import sys
from pathlib import Path

DIRECTIVE = re.compile(r'^\s*#(if|elif|else|endif)\b(.*)$')
CONST_RE = re.compile(r'MC_1_\d+_\d+')

# Version string -> index, mirror of settings.gradle's versionProperties list.
VERSIONS = [
    "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6",
    "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6",
    "1.21.7", "1.21.8", "1.21.9", "1.21.10", "1.21.11",
]
DEFAULT_DIRS = ["common", "fabric", "forge", "neoforge"]


class CondEval:
    """Safe evaluator for directive expressions (numbers, comparisons, && || !)."""

    def __init__(self, defs):
        # Substitute longest names first so MC_1_20_1 never matches inside MC_1_20_1x.
        self.names = sorted(defs, key=len, reverse=True)
        self.defs = defs

    def eval(self, expr):
        expr = expr.strip().strip("()").strip()
        # Java boolean operators -> Python
        expr = expr.replace("&&", " and ").replace("||", " or ")
        expr = re.sub(r"!(?!=)", " not ", expr)
        for name in self.names:
            expr = expr.replace(name, str(self.defs[name]))
        tree = ast.parse(expr, mode="eval")
        return bool(self._walk(tree.body))

    def _walk(self, node):
        if isinstance(node, ast.Constant):
            return node.value
        if isinstance(node, ast.Compare):
            ops = {ast.Lt: operator.lt, ast.Gt: operator.gt, ast.LtE: operator.le,
                   ast.GtE: operator.ge, ast.Eq: operator.eq, ast.NotEq: operator.ne}
            left = self._walk(node.left)
            return all(ops[type(op)](left, self._walk(c))
                       for op, c in zip(node.ops, node.comparators))
        if isinstance(node, ast.BoolOp):
            if isinstance(node.op, ast.And):
                return all(self._walk(v) for v in node.values)
            return any(self._walk(v) for v in node.values)
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
            return not self._walk(node.operand)
        raise ValueError(f"unsupported directive expression: {ast.dump(node)}")


def load_defs(path):
    defs = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            try:
                defs[key.strip()] = int(val.strip())
            except ValueError:
                pass  # non-integer constants are irrelevant to #if arithmetic
    return defs


def expand_file(src: Path, out: Path, cond: CondEval):
    """Evaluate the directive stack, write only active lines to out.

    Returns (src_line_count, out_line_count, directive_count). Always writes
    the output so the copy is a complete, usable source tree.
    """
    lines_out = []
    stack = []  # entries: [parent_active, taken, active]
    directives = 0
    src_lines = 0
    for line in src.read_text(encoding="utf-8").splitlines(keepends=True):
        src_lines += 1
        m = DIRECTIVE.match(line)
        if not m:
            if all(s[2] for s in stack):
                lines_out.append(line)
            continue
        kind, rest = m.group(1), m.group(2)
        directives += 1
        if kind == "if":
            parent_active = all(s[2] for s in stack)
            active = parent_active and cond.eval(rest)
            stack.append([parent_active, active, active])
        elif kind == "elif":
            parent_active, taken, active = stack[-1]
            if active:
                stack[-1][2] = False  # branch already taken; deactivate
            elif not taken:
                new_active = parent_active and cond.eval(rest)
                stack[-1][1] = new_active
                stack[-1][2] = new_active
        elif kind == "else":
            parent_active, taken, _ = stack[-1]
            stack[-1][2] = parent_active and not taken
        elif kind == "endif":
            if not stack:
                raise ValueError(f"{src}: unmatched #endif")
            stack.pop()
    if stack:
        raise ValueError(f"{src}: unterminated #if/#elif block")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(lines_out), encoding="utf-8")
    return src_lines, len(lines_out), directives


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mc_ver", nargs="?", help="target MC version, e.g. 1.20.4, or index")
    parser.add_argument("--defs", default="build.properties",
                        help="preprocessor constants file (default: build.properties)")
    parser.add_argument("--out", default=None, help="output root (default: build/jdt-view/<ver>)")
    parser.add_argument("dirs", nargs="*", default=DEFAULT_DIRS,
                        help="source roots to expand (default: common fabric forge neoforge)")
    args = parser.parse_args(argv)

    defs = load_defs(args.defs)
    if not defs:
        sys.exit(f"error: no constants in {args.defs}; run a Gradle build first "
                 f"(./gradlew help) to generate it")
    if args.mc_ver is None:
        mc_index = defs.get("MC_VER")
        if mc_index is None:
            sys.exit("error: MC_VER missing from defs; pass a version argument")
    elif args.mc_ver.isdigit():
        mc_index = int(args.mc_ver)
    else:
        try:
            mc_index = VERSIONS.index(args.mc_ver)
        except ValueError:
            sys.exit(f"error: unknown MC version {args.mc_ver}")
    defs["MC_VER"] = mc_index
    cond = CondEval(defs)

    version_label = VERSIONS[mc_index] if 0 <= mc_index < len(VERSIONS) else f"idx{mc_index}"
    out_root = Path(args.out) if args.out else Path("build") / "jdt-view" / version_label

    total_files = total_directives = 0
    for d in args.dirs:
        root = Path(d)
        if not root.is_dir():
            print(f"skip (missing): {d}")
            continue
        for src in sorted(root.rglob("*.java")):
            rel = src.relative_to(root)
            out = out_root / d / rel
            src_lines, out_lines, directives = expand_file(src, out, cond)
            total_files += 1
            total_directives += directives
            label = "expanded" if directives else "copied  "
            print(f"{label} {d}/{rel} ({src_lines}->{out_lines} lines)")
    print(f"\n{total_files} files -> {out_root}  (MC_VER={mc_index}, {version_label}; "
          f"{total_directives} directives evaluated)")


if __name__ == "__main__":
    main(sys.argv[1:])
